# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "GEUS Glaciology & Climate"
title_separator          : "-"
# subtitle                 : # site tagline that appears below site title in masthead
name                     : "GEUS Glaciology & Climate"
description              : "Research, monitoring and consultancy related to glaciology, climate and the environment"
# url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "GEUS-Glaciology-and-Climate/geus-glaciology-and-climate.github.io"
# teaser                   : "/assets/images/gk_logo_mini.png"
logo                     : "/assets/images/gk_logo.png"
# masthead_title           : 
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
search                   : true
# search_full_content      : # true, false (default)
# search_provider          : # lunr (default), algolia, google
# google:
#   search_engine_id       : # YOUR_SEARCH_ENGINE_ID
#   instant_search         : # false (default), true

# Analytics
# analytics:
#   provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "GEUS Glaciology & Climate"
  avatar           : "/assets/images/gk_logo.png"
  bio              : "The Department of Glaciology and Climate conducts research, monitoring and consultancy related to glaciology, climate and the environment, with one of our main activities being the monitoring of the Greenland Ice Sheet."
  location         : "Copenhagen, DK"
#   email            :
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.promice.dk/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PromiceGL"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GEUS-Glaciology-and-Climate"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PromiceGL"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GEUS-Glaciology-and-Climate"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://geusgitlab.geus.dk/"

# Reading Files
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Copenhagen"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
